"use client";
import { createContext, useContext, useState } from "react";
const productWithManyOptions = {
  id: 100,
  title: "Ultimate Customizable Hoodie",
  price: 80.0,
  status: "IN STOCK",
  image: "/cover.svg",
  rating: 4.8,
  reviews: [
    {
      authorid: 1,
      rating: 5,
      author: "Alice Johnson",
      date: "2 DAYS AGO",
      text: "Amazing quality! Love the color and fit.",
    },
    {
      authorid: 2,
      rating: 4,
      author: "Mohamed Tarek",
      date: "5 DAYS AGO",
      text: "Great hoodie, but took a while to ship.",
    },
    {
      authorid: 3,
      rating: 5,
      author: "Liam Smith",
      date: "1 WEEK AGO",
      text: "Super soft and comfy. Highly recommend!",
    },
    {
      authorid: 4,
      rating: 4,
      author: "Noor Hassan",
      date: "3 DAYS AGO",
      text: "Good fabric, nice design. Will buy again.",
    },
    {
      authorid: 5,
      rating: 5,
      author: "Carlos Mendez",
      date: "6 DAYS AGO",
      text: "Perfect for cold weather. Feels premium.",
    },
    {
      authorid: 6,
      rating: 5,
      author: "Emily Chen",
      date: "1 DAY AGO",
      text: "Color exactly as shown. Love it!",
    },
    {
      authorid: 7,
      rating: 5,
      author: "Fatima Ali",
      date: "4 DAYS AGO",
      text: "Comfortable and stylish. Great purchase.",
    },
    {
      authorid: 8,
      rating: 4,
      author: "John Doe",
      date: "1 WEEK AGO",
      text: "Good overall, but runs a bit large.",
    },
    {
      authorid: 9,
      rating: 5,
      author: "Sarah Kim",
      date: "2 WEEKS AGO",
      text: "Best hoodie I’ve ever owned.",
    },
    {
      authorid: 10,
      rating: 5,
      author: "Ahmed Adel",
      date: "5 DAYS AGO",
      text: "Material feels amazing and very warm.",
    },
    {
      authorid: 11,
      rating: 4,
      author: "Chloe Lee",
      date: "3 DAYS AGO",
      text: "Nice but I wish it had more pockets.",
    },
    {
      authorid: 12,
      rating: 5,
      author: "Omar Farouk",
      date: "1 DAY AGO",
      text: "Fits perfectly. Looks very sleek.",
    },
    {
      authorid: 13,
      rating: 5,
      author: "Emma Watson",
      date: "6 DAYS AGO",
      text: "So soft and cozy. My new favorite!",
    },
    {
      authorid: 14,
      rating: 4,
      author: "Aliya Khan",
      date: "1 WEEK AGO",
      text: "Really nice design and warm enough.",
    },
    {
      authorid: 15,
      rating: 5,
      author: "Jake Miller",
      date: "2 DAYS AGO",
      text: "Great hoodie, great service!",
    },
    {
      authorid: 16,
      rating: 5,
      author: "Layla Mahmoud",
      date: "4 DAYS AGO",
      text: "Top-notch quality and fast delivery.",
    },
    {
      authorid: 17,
      rating: 4,
      author: "Daniel Green",
      date: "3 DAYS AGO",
      text: "Hood is a bit tight, otherwise perfect.",
    },
    {
      authorid: 18,
      rating: 5,
      author: "Sophia Brown",
      date: "1 WEEK AGO",
      text: "Stylish and warm. I love it!",
    },
    {
      authorid: 19,
      rating: 5,
      author: "Abdulrahman Zaki",
      date: "2 DAYS AGO",
      text: "Worth every penny. Excellent quality.",
    },
    {
      authorid: 20,
      rating: 4,
      author: "Mia Wilson",
      date: "6 DAYS AGO",
      text: "A bit pricey, but worth it.",
    },
    {
      authorid: 21,
      rating: 5,
      author: "George Wang",
      date: "1 WEEK AGO",
      text: "This hoodie is 🔥🔥🔥",
    },
    {
      authorid: 22,
      rating: 5,
      author: "Leila Haddad",
      date: "2 DAYS AGO",
      text: "Bought one for my brother too!",
    },
    {
      authorid: 23,
      rating: 4,
      author: "Tomás García",
      date: "5 DAYS AGO",
      text: "Very good quality. I'd buy again.",
    },
    {
      authorid: 24,
      rating: 5,
      author: "Natalie Park",
      date: "3 DAYS AGO",
      text: "So warm and fits just right.",
    },
    {
      authorid: 25,
      rating: 5,
      author: "Ismail Noor",
      date: "1 WEEK AGO",
      text: "Perfect for winter nights.",
    },
    {
      authorid: 26,
      rating: 4,
      author: "Aisha Musa",
      date: "6 DAYS AGO",
      text: "Color faded slightly after wash.",
    },
    {
      authorid: 27,
      rating: 5,
      author: "Samir Patel",
      date: "4 DAYS AGO",
      text: "Excellent stitching and quality.",
    },
    {
      authorid: 28,
      rating: 5,
      author: "Linda Scott",
      date: "2 DAYS AGO",
      text: "My go-to hoodie from now on.",
    },
    {
      authorid: 29,
      rating: 5,
      author: "Youssef Amin",
      date: "3 DAYS AGO",
      text: "Super cozy and cool looking!",
    },
    {
      authorid: 30,
      rating: 4,
      author: "Elena Petrova",
      date: "1 WEEK AGO",
      text: "Really nice, just size up if needed.",
    },
    {
      authorid: 31,
      rating: 5,
      author: "Benjamin Lee",
      date: "2 DAYS AGO",
      text: "Feels like luxury on your skin!",
    },
    {
      authorid: 32,
      rating: 5,
      author: "Sana Khalid",
      date: "5 DAYS AGO",
      text: "Highly recommend this hoodie.",
    },
    {
      authorid: 33,
      rating: 4,
      author: "David Thompson",
      date: "3 DAYS AGO",
      text: "A little thick for summer, great for fall.",
    },
    {
      authorid: 34,
      rating: 5,
      author: "Julia Davis",
      date: "1 WEEK AGO",
      text: "Looks amazing. Feels better!",
    },
    {
      authorid: 35,
      rating: 5,
      author: "Mona Elbaz",
      date: "6 DAYS AGO",
      text: "Color selection is awesome.",
    },
    {
      authorid: 36,
      rating: 4,
      author: "Zack Taylor",
      date: "2 DAYS AGO",
      text: "Could be cheaper, but happy with it.",
    },
    {
      authorid: 37,
      rating: 5,
      author: "Nada Yassin",
      date: "5 DAYS AGO",
      text: "10/10. Buying again in another color.",
    },
    {
      authorid: 38,
      rating: 5,
      author: "James Carter",
      date: "4 DAYS AGO",
      text: "Love the minimalist design.",
    },
    {
      authorid: 39,
      rating: 5,
      author: "Aya Selim",
      date: "1 WEEK AGO",
      text: "Exactly what I was looking for!",
    },
    {
      authorid: 40,
      rating: 4,
      author: "Eric Jones",
      date: "6 DAYS AGO",
      text: "Pretty good for the price.",
    },
    {
      authorid: 41,
      rating: 5,
      author: "Khadija Nabil",
      date: "3 DAYS AGO",
      text: "Love love love this hoodie!",
    },
    {
      authorid: 42,
      rating: 5,
      author: "Tarek Mohamed",
      date: "2 DAYS AGO",
      text: "The fabric is so rich and thick.",
    },
    {
      authorid: 43,
      rating: 4,
      author: "Hannah Gold",
      date: "1 WEEK AGO",
      text: "Good, but took 4 days to arrive.",
    },
    {
      authorid: 44,
      rating: 5,
      author: "Yara Osman",
      date: "5 DAYS AGO",
      text: "My friends keep asking where I got it!",
    },
    {
      authorid: 45,
      rating: 5,
      author: "Leon Wright",
      date: "3 DAYS AGO",
      text: "So good I bought another color!",
    },
    {
      authorid: 46,
      rating: 5,
      author: "Amira Fathy",
      date: "2 DAYS AGO",
      text: "Worth every pound. Love it.",
    },
    {
      authorid: 47,
      rating: 4,
      author: "Owen Kim",
      date: "4 DAYS AGO",
      text: "Nice but not true to size.",
    },
    {
      authorid: 48,
      rating: 5,
      author: "Iman Hegazy",
      date: "1 WEEK AGO",
      text: "Definitely a wardrobe essential!",
    },
    {
      authorid: 49,
      rating: 5,
      author: "Victor Hugo",
      date: "6 DAYS AGO",
      text: "Very pleased with this product.",
    },
    {
      authorid: 50,
      rating: 5,
      author: "Salma Rami",
      date: "2 DAYS AGO",
      text: "Elegant, comfy, and durable.",
    },
  ],
  details: {
    description: `This hoodie offers the ultimate comfort, design, and customization. Whether you're out on the streets or chilling at home, this hoodie delivers.`,
    features: [
      "Custom Colors",
      "Super Soft Fabric",
      "Heavyweight Material",
      "Unisex Fit",
    ],
  },
  colors: [
    { color: "#000000", image: "/cover.svg" },
    { color: "#FFFFFF", image: "/cover.svg" },
    { color: "#FF0000", image: "/cover.svg" },
    { color: "#00FF00", image: "/cover.svg" },
    { color: "#0000FF", image: "/cover.svg" },
    { color: "#FFFF00", image: "/cover.svg" },
    { color: "#FF00FF", image: "/cover.svg" },
    { color: "#00FFFF", image: "/cover.svg" },
    { color: "#808080", image: "/cover.svg" },
    { color: "#F97316", image: "/cover.svg" },
  ],
  sizes: ["XS", "S", "M", "L", "XL", "XXL"],
  tag: "bestselling",
  category: "Hoodies",
};
const Products = [
  {
    id: 1,
    title: "Explorer Jacket",
    price: 99.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 1,
        rating: 5,
        author: "Alice Smith",
        date: "3 DAYS AGO",
        text: "Stylish and durable!",
      },
    ],
    details: {
      description: "Perfect jacket for outdoor adventures.",
      features: ["Waterproof", "Thermal Lining"],
    },
    colors: [
      { color: "#000000", image: "/cover.svg" },
      { color: "#FFFFFF", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tag: "featured",
    category: "Jackets",
  },
  {
    id: 2,
    title: "Urban Sneakers",
    price: 79.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 2,
        rating: 4,
        author: "Bob Jones",
        date: "5 DAYS AGO",
        text: "Comfortable and affordable.",
      },
    ],
    details: {
      description: "Lightweight sneakers for daily use.",
      features: ["Foam Insole", "Slip Resistant"],
    },
    colors: [
      { color: "#FFFFFF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
    ],
    sizes: ["40", "41", "42", "43"],
    tag: "bestselling",
    category: "Shoes",
  },
  {
    id: 3,
    title: "Comfy Hoodie",
    price: 49.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.8,
    reviews: [
      {
        authorid: 3,
        rating: 5,
        author: "Carla Green",
        date: "1 WEEK AGO",
        text: "Super warm and cozy!",
      },
    ],
    details: {
      description: "Oversized hoodie for ultimate comfort.",
      features: ["Soft Fabric", "Warm Fit"],
    },
    colors: [
      { color: "#6B7280", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#FCD34D", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "latest",
    category: "Hoodies",
  },
  {
    id: 4,
    title: "Active T-Shirt",
    price: 29.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 4,
        rating: 4,
        author: "Derek Hill",
        date: "2 DAYS AGO",
        text: "Good for workouts.",
      },
    ],
    details: {
      description: "Breathable t-shirt for sports activities.",
      features: ["Quick Dry", "Stretchy Material"],
    },
    colors: [
      { color: "#F59E0B", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#1E3A8A", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "featured",
    category: "T-Shirts",
  },
  {
    id: 5,
    title: "Slim Fit Jeans",
    price: 59.95,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 5,
        rating: 5,
        author: "Eve Dawson",
        date: "6 DAYS AGO",
        text: "Fits perfectly!",
      },
    ],
    details: {
      description: "Classic slim-fit jeans.",
      features: ["Stretch Denim", "Mid Rise"],
    },
    colors: [
      { color: "#1E3A8A", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["30", "32", "34", "36"],
    tag: "bestselling",
    category: "Pants",
  },
  {
    id: 6,
    title: "Leather Wallet",
    price: 24.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.0,
    reviews: [
      {
        authorid: 6,
        rating: 4,
        author: "Frank Moore",
        date: "4 DAYS AGO",
        text: "Compact and nice leather.",
      },
    ],
    details: {
      description: "Handmade wallet from genuine leather.",
      features: ["Compact Design", "Multiple Pockets"],
    },
    colors: [
      { color: "#111827", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 7,
    title: "Graphic Tee",
    price: 27.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 3.9,
    reviews: [
      {
        authorid: 7,
        rating: 3,
        author: "Grace Chen",
        date: "8 DAYS AGO",
        text: "Cool print, but thin fabric.",
      },
    ],
    details: {
      description: "Trendy graphic printed t-shirt.",
      features: ["Soft Cotton", "Bold Print"],
    },
    colors: [
      { color: "#F87171", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#6B7280", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "featured",
    category: "T-Shirts",
  },
  {
    id: 8,
    title: "Winter Beanie",
    price: 15.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.4,
    reviews: [
      {
        authorid: 8,
        rating: 5,
        author: "Henry Lee",
        date: "1 DAY AGO",
        text: "Very warm and stretchy.",
      },
    ],
    details: {
      description: "Knit beanie ideal for winter days.",
      features: ["Wool Blend", "Stretch Fit"],
    },
    colors: [
      { color: "#9CA3AF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "bestselling",
    category: "Accessories",
  },
  {
    id: 9,
    title: "Classic Dress Shirt",
    price: 39.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 9,
        rating: 4,
        author: "Ivy Morgan",
        date: "2 WEEKS AGO",
        text: "Fits great, easy to iron.",
      },
    ],
    details: {
      description: "Formal shirt perfect for office wear.",
      features: ["Easy Iron", "Slim Fit"],
    },
    colors: [
      { color: "#FFFFFF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tag: "latest",
    category: "Shirts",
  },
  {
    id: 10,
    title: "Jogger Pants",
    price: 44.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 10,
        rating: 5,
        author: "Jack Black",
        date: "5 DAYS AGO",
        text: "Soft and fits well!",
      },
    ],
    details: {
      description: "Everyday joggers for casual wear.",
      features: ["Drawstring Waist", "Tapered Leg"],
    },
    colors: [
      { color: "#374151", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Pants",
  },
  {
    id: 11,
    title: "Summer Tank",
    price: 22.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.1,
    reviews: [
      {
        authorid: 11,
        rating: 4,
        author: "Kate Allen",
        date: "2 DAYS AGO",
        text: "Nice fit for summer.",
      },
    ],
    details: {
      description: "Lightweight tank for hot weather.",
      features: ["Breathable", "Loose Fit"],
    },
    colors: [
      { color: "#FCD34D", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "latest",
    category: "Tank Tops",
  },
  {
    id: 12,
    title: "Running Shorts",
    price: 25.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 12,
        rating: 4,
        author: "Liam Scott",
        date: "4 DAYS AGO",
        text: "Perfect for workouts.",
      },
    ],
    details: {
      description: "Shorts with lightweight material.",
      features: ["Elastic Waist", "Quick Dry"],
    },
    colors: [
      { color: "#D1D5DB", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "featured",
    category: "Shorts",
  },
  {
    id: 13,
    title: "Denim Shirt",
    price: 41.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.4,
    reviews: [
      {
        authorid: 13,
        rating: 5,
        author: "Mona Ray",
        date: "1 WEEK AGO",
        text: "Stylish and tough.",
      },
    ],
    details: {
      description: "Classic denim shirt with buttons.",
      features: ["Durable Fabric", "Modern Cut"],
    },
    colors: [
      { color: "#3B82F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Shirts",
  },
  {
    id: 14,
    title: "Everyday Belt",
    price: 19.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.0,
    reviews: [
      {
        authorid: 14,
        rating: 4,
        author: "Nora Adams",
        date: "6 DAYS AGO",
        text: "Good quality for price.",
      },
    ],
    details: {
      description: "Belt for both casual and formal wear.",
      features: ["Leather Finish", "Metal Buckle"],
    },
    colors: [
      { color: "#000000", image: "/cover.svg" },
      { color: "#F59E0B", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 15,
    title: "Canvas Tote",
    price: 17.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 15,
        rating: 5,
        author: "Omar Ali",
        date: "3 DAYS AGO",
        text: "Spacious and strong.",
      },
    ],
    details: {
      description: "Eco-friendly tote bag for daily use.",
      features: ["Durable", "Washable"],
    },
    colors: [
      { color: "#F3F4F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "featured",
    category: "Bags",
  },
  {
    id: 16,
    title: "Fleece Hoodie",
    price: 56.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.7,
    reviews: [
      {
        authorid: 16,
        rating: 5,
        author: "Paul Green",
        date: "2 DAYS AGO",
        text: "Very soft and warm.",
      },
    ],
    details: {
      description: "Perfect hoodie for winter.",
      features: ["Thick Fabric", "Front Pocket"],
    },
    colors: [
      { color: "#4B5563", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Hoodies",
  },
  {
    id: 17,
    title: "Soft Pajama Set",
    price: 39.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 17,
        rating: 5,
        author: "Quinn Waters",
        date: "1 DAY AGO",
        text: "Super comfy!",
      },
    ],
    details: {
      description: "Sleepwear with ultra soft fabric.",
      features: ["Breathable", "Stretch Material"],
    },
    colors: [
      { color: "#E5E7EB", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "featured",
    category: "Sleepwear",
  },
  {
    id: 18,
    title: "Classic Loafers",
    price: 68.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 18,
        rating: 4,
        author: "Rita Ford",
        date: "2 WEEKS AGO",
        text: "Comfortable fit.",
      },
    ],
    details: {
      description: "Timeless loafers with leather lining.",
      features: ["Genuine Leather", "Slip-On"],
    },
    colors: [
      { color: "#A16207", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["41", "42", "43"],
    tag: "bestselling",
    category: "Shoes",
  },
  {
    id: 19,
    title: "Basic V-Neck Tee",
    price: 26.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 19,
        rating: 4,
        author: "Steve Clark",
        date: "5 DAYS AGO",
        text: "Soft and light.",
      },
    ],
    details: {
      description: "V-neck tee for everyday wear.",
      features: ["Lightweight", "Stretch Fit"],
    },
    colors: [
      { color: "#F9FAFB", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "latest",
    category: "T-Shirts",
  },
  {
    id: 20,
    title: "Wool Scarf",
    price: 23.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.8,
    reviews: [
      {
        authorid: 20,
        rating: 5,
        author: "Tina Young",
        date: "6 DAYS AGO",
        text: "Soft and cozy.",
      },
    ],
    details: {
      description: "Warm scarf made of pure wool.",
      features: ["Fringed Ends", "Soft Weave"],
    },
    colors: [
      { color: "#6EE7B7", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "featured",
    category: "Accessories",
  },
  {
    id: 21,
    title: "Slim Fit Blazer",
    price: 75.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 21,
        rating: 5,
        author: "Yousef Hamdy",
        date: "3 DAYS AGO",
        text: "Elegant and professional.",
      },
    ],
    details: {
      description: "Tailored blazer for formal occasions.",
      features: ["Modern Cut", "Inner Pockets"],
    },
    colors: [
      { color: "#1E293B", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Jackets",
  },
  {
    id: 22,
    title: "Workout Leggings",
    price: 34.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.4,
    reviews: [
      {
        authorid: 22,
        rating: 4,
        author: "Amira Said",
        date: "1 WEEK AGO",
        text: "Comfortable for running.",
      },
    ],
    details: {
      description: "Stretchable leggings for fitness.",
      features: ["High Waist", "Breathable"],
    },
    colors: [
      { color: "#9333EA", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "latest",
    category: "Activewear",
  },
  {
    id: 23,
    title: "Rainproof Jacket",
    price: 60.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.7,
    reviews: [
      {
        authorid: 23,
        rating: 5,
        author: "Mohamed Anwar",
        date: "4 DAYS AGO",
        text: "Great for wet weather.",
      },
    ],
    details: {
      description: "Water-resistant jacket with hood.",
      features: ["Windproof", "Adjustable Fit"],
    },
    colors: [
      { color: "#2563EB", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "featured",
    category: "Jackets",
  },
  {
    id: 24,
    title: "Casual Linen Shirt",
    price: 38.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 24,
        rating: 4,
        author: "Laila Osama",
        date: "5 DAYS AGO",
        text: "Perfect for summer outings.",
      },
    ],
    details: {
      description: "Light linen shirt for hot days.",
      features: ["Loose Fit", "Breathable Material"],
    },
    colors: [
      { color: "#F3F4F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "latest",
    category: "Shirts",
  },
  {
    id: 25,
    title: "Leather Crossbody Bag",
    price: 59.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.8,
    reviews: [
      {
        authorid: 25,
        rating: 5,
        author: "Rami Hassan",
        date: "3 DAYS AGO",
        text: "Very practical and chic.",
      },
    ],
    details: {
      description: "Compact leather bag with adjustable strap.",
      features: ["Multiple Compartments", "Secure Zip"],
    },
    colors: [
      { color: "#92400E", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "bestselling",
    category: "Bags",
  },
  {
    id: 26,
    title: "Graphic Sweatshirt",
    price: 45.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 26,
        rating: 4,
        author: "Dina Gamil",
        date: "6 DAYS AGO",
        text: "Love the print!",
      },
    ],
    details: {
      description: "Soft sweatshirt with bold graphic.",
      features: ["Cotton Blend", "Relaxed Fit"],
    },
    colors: [
      { color: "#E879F9", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tag: "featured",
    category: "Sweaters",
  },
  {
    id: 27,
    title: "Tech Gloves",
    price: 21.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.1,
    reviews: [
      {
        authorid: 27,
        rating: 4,
        author: "Ahmed Ezz",
        date: "1 WEEK AGO",
        text: "Works well with phones.",
      },
    ],
    details: {
      description: "Touchscreen-compatible winter gloves.",
      features: ["Warm Interior", "Touch Sensors"],
    },
    colors: [
      { color: "#111827", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 28,
    title: "Foldable Backpack",
    price: 36.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 28,
        rating: 4,
        author: "Karim Samir",
        date: "2 DAYS AGO",
        text: "Convenient for travel.",
      },
    ],
    details: {
      description: "Backpack that folds into a pouch.",
      features: ["Lightweight", "Water Resistant"],
    },
    colors: [
      { color: "#FACC15", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "featured",
    category: "Bags",
  },
  {
    id: 29,
    title: "Chunky Sneakers",
    price: 70.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.9,
    reviews: [
      {
        authorid: 29,
        rating: 5,
        author: "Ziad Ahmed",
        date: "1 DAY AGO",
        text: "Trendy and comfy.",
      },
    ],
    details: {
      description: "Bold sneakers for casual wear.",
      features: ["Thick Sole", "Breathable Mesh"],
    },
    colors: [
      { color: "#E11D48", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["40", "41", "42", "43"],
    tag: "bestselling",
    category: "Shoes",
  },
  {
    id: 30,
    title: "Cotton Joggers",
    price: 43.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 30,
        rating: 4,
        author: "Habiba Tarek",
        date: "4 DAYS AGO",
        text: "So soft and flexible.",
      },
    ],
    details: {
      description: "Everyday joggers with drawstring.",
      features: ["Soft Touch", "Tapered Leg"],
    },
    colors: [
      { color: "#9CA3AF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tag: "featured",
    category: "Pants",
  },
  {
    id: 31,
    title: "Classic Leather Jacket",
    price: 129.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.7,
    reviews: [
      {
        authorid: 31,
        rating: 5,
        author: "David Miller",
        date: "1 WEEK AGO",
        text: "Stylish and warm!",
      },
      {
        authorid: 32,
        rating: 4,
        author: "Sophia Lee",
        date: "2 WEEKS AGO",
        text: "Great fit, but a bit pricey.",
      },
      {
        authorid: 33,
        rating: 5,
        author: "Chris Evans",
        date: "3 DAYS AGO",
        text: "Perfect for winter nights.",
      },
    ],
    details: {
      description: "Timeless leather jacket with premium finish.",
      features: ["Soft Lining", "Adjustable Cuffs"],
    },
    colors: [
      { color: "#000000", image: "/cover.svg" },
      { color: "#F87171", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Jackets",
  },
  {
    id: 32,
    title: "Running Shoes Pro",
    price: 89.95,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 34,
        rating: 5,
        author: "Liam Carter",
        date: "5 DAYS AGO",
        text: "Super comfortable for long runs.",
      },
      {
        authorid: 35,
        rating: 4,
        author: "Emma Walker",
        date: "1 WEEK AGO",
        text: "Good grip and breathable.",
      },
      {
        authorid: 36,
        rating: 4,
        author: "Noah Reed",
        date: "10 DAYS AGO",
        text: "Wore them all day at work — no pain!",
      },
    ],
    details: {
      description: "High-performance running shoes with cushioned sole.",
      features: ["Lightweight", "Arch Support"],
    },
    colors: [
      { color: "#FFFFFF", image: "/cover.svg" },
      { color: "#0000FF", image: "/cover.svg" },
    ],
    sizes: ["40", "41", "42", "43"],
    tag: "featured",
    category: "Shoes",
  },
  {
    id: 33,
    title: "Striped Polo Shirt",
    price: 34.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 37,
        rating: 4,
        author: "Oliver Stone",
        date: "6 DAYS AGO",
        text: "Nice fabric and classic style.",
      },
      {
        authorid: 38,
        rating: 5,
        author: "Isabella Moore",
        date: "2 WEEKS AGO",
        text: "My husband loves it!",
      },
    ],
    details: {
      description: "Elegant striped polo shirt for casual occasions.",
      features: ["Cotton Blend", "Breathable"],
    },
    colors: [
      { color: "#FCD34D", image: "/cover.svg" },
      { color: "#1E3A8A", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "latest",
    category: "T-Shirts",
  },
  {
    id: 34,
    title: "Winter Boots",
    price: 65.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 39,
        rating: 5,
        author: "James Bond",
        date: "3 DAYS AGO",
        text: "Kept my feet dry in snow!",
      },
      {
        authorid: 40,
        rating: 4,
        author: "Chloe Kim",
        date: "1 WEEK AGO",
        text: "Warm and stylish.",
      },
      {
        authorid: 41,
        rating: 4,
        author: "Lucas Hall",
        date: "8 DAYS AGO",
        text: "Perfect for cold weather.",
      },
    ],
    details: {
      description: "Waterproof boots for harsh winter conditions.",
      features: ["Insulated Sole", "Non-Slip"],
    },
    colors: [
      { color: "#111827", image: "/cover.svg" },
      { color: "#FACC15", image: "/cover.svg" },
    ],
    sizes: ["41", "42", "43", "44"],
    tag: "bestselling",
    category: "Shoes",
  },
  {
    id: 35,
    title: "Denim Shorts",
    price: 28.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 42,
        rating: 4,
        author: "Zara Ahmed",
        date: "5 DAYS AGO",
        text: "Great summer shorts!",
      },
      {
        authorid: 43,
        rating: 5,
        author: "Nina Patel",
        date: "10 DAYS AGO",
        text: "Fit perfectly and very trendy.",
      },
    ],
    details: {
      description: "Casual denim shorts for beach or city wear.",
      features: ["Frayed Hem", "Comfort Fit"],
    },
    colors: [
      { color: "#3B82F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "latest",
    category: "Shorts",
  },
  {
    id: 36,
    title: "Flannel Shirt",
    price: 42.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.4,
    reviews: [
      {
        authorid: 44,
        rating: 5,
        author: "Mason Hill",
        date: "1 WEEK AGO",
        text: "Cozy and warm.",
      },
      {
        authorid: 45,
        rating: 4,
        author: "Emily White",
        date: "12 DAYS AGO",
        text: "Perfect for autumn.",
      },
    ],
    details: {
      description: "Classic flannel shirt for chilly days.",
      features: ["Plaid Design", "Soft Fabric"],
    },
    colors: [
      { color: "#D1D5DB", image: "/cover.svg" },
      { color: "#DC2626", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "featured",
    category: "Shirts",
  },
  {
    id: 37,
    title: "Sports Bra",
    price: 25.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 46,
        rating: 5,
        author: "Sarah Jones",
        date: "3 DAYS AGO",
        text: "Excellent support during workouts.",
      },
      {
        authorid: 47,
        rating: 4,
        author: "Maya Lopez",
        date: "6 DAYS AGO",
        text: "Very comfortable material.",
      },
      {
        authorid: 48,
        rating: 4,
        author: "Leah Chen",
        date: "1 WEEK AGO",
        text: "Fast drying and breathable.",
      },
    ],
    details: {
      description: "High-support sports bra for gym or yoga.",
      features: ["Moisture Wicking", "Wire-Free"],
    },
    colors: [
      { color: "#BE123C", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["S", "M", "L"],
    tag: "latest",
    category: "Activewear",
  },
  {
    id: 38,
    title: "Puffer Vest",
    price: 59.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 49,
        rating: 5,
        author: "Ethan Cole",
        date: "2 DAYS AGO",
        text: "Perfect layering piece for winter.",
      },
      {
        authorid: 50,
        rating: 5,
        author: "Sophie Turner",
        date: "5 DAYS AGO",
        text: "Lightweight yet so warm.",
      },
    ],
    details: {
      description: "Warm puffer vest for cold climates.",
      features: ["Windproof", "Packable Design"],
    },
    colors: [
      { color: "#FACC15", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Jackets",
  },
  {
    id: 39,
    title: "Slim Fit Chinos",
    price: 49.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 51,
        rating: 4,
        author: "William Scott",
        date: "1 WEEK AGO",
        text: "Great fit and versatile.",
      },
      {
        authorid: 52,
        rating: 5,
        author: "Amelia Brown",
        date: "10 DAYS AGO",
        text: "Ideal for both office and weekend.",
      },
    ],
    details: {
      description: "Modern slim-fit chino pants.",
      features: ["Stretch Material", "Flat Front"],
    },
    colors: [
      { color: "#A16207", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["30", "32", "34", "36"],
    tag: "featured",
    category: "Pants",
  },
  {
    id: 40,
    title: "Canvas Backpack",
    price: 39.95,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.4,
    reviews: [
      {
        authorid: 53,
        rating: 5,
        author: "Daniel Morgan",
        date: "4 DAYS AGO",
        text: "Spacious and durable.",
      },
      {
        authorid: 54,
        rating: 4,
        author: "Grace Taylor",
        date: "8 DAYS AGO",
        text: "Good for school or travel.",
      },
      {
        authorid: 55,
        rating: 4,
        author: "Benjamin Cruz",
        date: "2 WEEKS AGO",
        text: "Comfy straps and lots of pockets.",
      },
    ],
    details: {
      description: "Everyday backpack made from strong canvas.",
      features: ["Multiple Pockets", "Reinforced Base"],
    },
    colors: [
      { color: "#F9FAFB", image: "/cover.svg" },
      { color: "#1F2937", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "bestselling",
    category: "Bags",
  },
  {
    id: 41,
    title: "Silk Scarf",
    price: 22.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.7,
    reviews: [
      {
        authorid: 56,
        rating: 5,
        author: "Maria Sanchez",
        date: "3 DAYS AGO",
        text: "So soft and elegant.",
      },
      {
        authorid: 57,
        rating: 5,
        author: "Lily Thompson",
        date: "1 WEEK AGO",
        text: "Beautiful design and quality.",
      },
    ],
    details: {
      description: "Luxury silk scarf for formal events.",
      features: ["Handmade Edges", "Lightweight"],
    },
    colors: [
      { color: "#F59E0B", image: "/cover.svg" },
      { color: "#EC4899", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "featured",
    category: "Accessories",
  },
  {
    id: 42,
    title: "Swim Trunks",
    price: 29.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 58,
        rating: 4,
        author: "Jack Robinson",
        date: "5 DAYS AGO",
        text: "Quick-drying and comfortable.",
      },
      {
        authorid: 59,
        rating: 4,
        author: "Max Rivera",
        date: "10 DAYS AGO",
        text: "Great for the pool or beach.",
      },
    ],
    details: {
      description: "Sporty swim trunks for active water use.",
      features: ["Mesh Liner", "Drawstring Waist"],
    },
    colors: [
      { color: "#3B82F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "latest",
    category: "Swimwear",
  },
  {
    id: 43,
    title: "Knit Sweater",
    price: 52.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 60,
        rating: 5,
        author: "Natalie Brooks",
        date: "2 DAYS AGO",
        text: "Cozy and stylish.",
      },
      {
        authorid: 61,
        rating: 4,
        author: "Charlotte Davis",
        date: "1 WEEK AGO",
        text: "Soft fabric and great cut.",
      },
    ],
    details: {
      description: "Warm knit sweater for winter months.",
      features: ["Ribbed Design", "Oversized Fit"],
    },
    colors: [
      { color: "#E5E7EB", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "featured",
    category: "Sweaters",
  },
  {
    id: 44,
    title: "Sun Hat",
    price: 18.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.1,
    reviews: [
      {
        authorid: 62,
        rating: 4,
        author: "Anna Foster",
        date: "6 DAYS AGO",
        text: "Good shade and light to carry.",
      },
      {
        authorid: 63,
        rating: 4,
        author: "Hannah Price",
        date: "2 WEEKS AGO",
        text: "Perfect for beach trips.",
      },
    ],
    details: {
      description: "Wide-brim sun hat for UV protection.",
      features: ["Foldable Design", "Breathable Material"],
    },
    colors: [
      { color: "#F3F4F6", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 45,
    title: "Cargo Pants",
    price: 46.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.3,
    reviews: [
      {
        authorid: 64,
        rating: 4,
        author: "Tommy Nguyen",
        date: "1 WEEK AGO",
        text: "Lots of pockets and comfy fit.",
      },
      {
        authorid: 65,
        rating: 5,
        author: "Jordan Allen",
        date: "5 DAYS AGO",
        text: "Great for outdoor activities.",
      },
    ],
    details: {
      description: "Utility cargo pants with multiple pockets.",
      features: ["Zippered Pockets", "Rugged Fabric"],
    },
    colors: [
      { color: "#374151", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "bestselling",
    category: "Pants",
  },
  {
    id: 46,
    title: "Winter Gloves",
    price: 19.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.2,
    reviews: [
      {
        authorid: 66,
        rating: 4,
        author: "Ella Parker",
        date: "3 DAYS AGO",
        text: "Keeps hands warm even in freezing temps.",
      },
      {
        authorid: 67,
        rating: 4,
        author: "Mia Bennett",
        date: "10 DAYS AGO",
        text: "Nice grip and soft inside.",
      },
    ],
    details: {
      description: "Insulated gloves for cold weather.",
      features: ["Grip Texture", "Thermal Lining"],
    },
    colors: [
      { color: "#111827", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 47,
    title: "Travel Duffel Bag",
    price: 54.0,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.6,
    reviews: [
      {
        authorid: 68,
        rating: 5,
        author: "Anthony Ramirez",
        date: "2 DAYS AGO",
        text: "Perfect size for weekend trips.",
      },
      {
        authorid: 69,
        rating: 5,
        author: "Claire Mitchell",
        date: "1 WEEK AGO",
        text: "Durable and spacious.",
      },
    ],
    details: {
      description: "Versatile duffel bag for short travels.",
      features: ["Detachable Strap", "Water Resistant"],
    },
    colors: [
      { color: "#9CA3AF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "bestselling",
    category: "Bags",
  },
  {
    id: 48,
    title: "Baseball Cap",
    price: 14.5,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.0,
    reviews: [
      {
        authorid: 70,
        rating: 4,
        author: "Joshua King",
        date: "6 DAYS AGO",
        text: "Good fit and adjustable strap.",
      },
      {
        authorid: 71,
        rating: 4,
        author: "Avery Brooks",
        date: "12 DAYS AGO",
        text: "Classic look and lightweight.",
      },
    ],
    details: {
      description: "Adjustable baseball cap for daily wear.",
      features: ["Ventilation Holes", "Adjustable Back"],
    },
    colors: [
      { color: "#0000FF", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["One Size"],
    tag: "latest",
    category: "Accessories",
  },
  {
    id: 49,
    title: "Fleece Pullover",
    price: 49.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.5,
    reviews: [
      {
        authorid: 72,
        rating: 5,
        author: "Gabriel Adams",
        date: "3 DAYS AGO",
        text: "Super soft and cozy.",
      },
      {
        authorid: 73,
        rating: 4,
        author: "Brooklyn Simmons",
        date: "1 WEEK AGO",
        text: "Great for lazy Sundays.",
      },
    ],
    details: {
      description: "Warm fleece pullover for relaxed days.",
      features: ["Loose Fit", "Front Pocket"],
    },
    colors: [
      { color: "#4B5563", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L", "XL"],
    tag: "featured",
    category: "Sweaters",
  },
  {
    id: 50,
    title: "Flip Flops",
    price: 12.99,
    status: "IN STOCK",
    image: "/cover.svg",
    rating: 4.1,
    reviews: [
      {
        authorid: 74,
        rating: 4,
        author: "Luna Hayes",
        date: "5 DAYS AGO",
        text: "Light and easy to pack.",
      },
      {
        authorid: 75,
        rating: 4,
        author: "Mason Rogers",
        date: "10 DAYS AGO",
        text: "Good for the beach or home.",
      },
    ],
    details: {
      description: "Comfortable flip flops for casual use.",
      features: ["Flexible Sole", "Non-Slip"],
    },
    colors: [
      { color: "#FCD34D", image: "/cover.svg" },
      { color: "#000000", image: "/cover.svg" },
    ],
    sizes: ["M", "L"],
    tag: "latest",
    category: "Shoes",
  },
  productWithManyOptions,
];

const categories = [...new Set(Products.map((p) => p.category))];

const colors = [
  ...new Set(Products.flatMap((p) => p.colors?.map((c) => c.color) || [])),
];
const sizes = [...new Set(Products.flatMap((p) => p.sizes || []))];

const ProductsContext = createContext();

export const ProductsProvider = ({ children }) => {
  const [products, setProducts] = useState(Products);

  return (
    <ProductsContext.Provider value={{ products, categories, colors, sizes }}>
      {children}
    </ProductsContext.Provider>
  );
};

export const useProducts = () => useContext(ProductsContext);
